name: 'C++ CI'

on:
  push:
    branches:
      - main
      - test-branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: cmake --preset clang-sanitizers

      - name: Build
        run: cmake --build --preset clang-sanitizers
        
      - name: Run
        run: ./build/clang-sanitizers/ci-cd-sanitizers-lab1
